### PR TITLE
Sb.post js

### PR DESCRIPTION
**Pull request by SonaliBhagwatkar**
Hi All,

Added functionality to like the post;

- Added the html code for implementing liking the blog post
- Added the JS code for implementing liking the blog post
- Added the css code for implementing liking the blog post

Kindly review the same.

### CODE REVIEW

**Review by bharathtakkalki — APPROVED** [review]
Approved

**Review by MeAmatuer — COMMENTED** [review]
There is an illegal character on line 36 in post.html

**Review by Pearl1594 — APPROVED** [review]
Looks good

**Review by MeAmatuer — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
